name: GPT Translate per Commit

on:
  push:
    branches:
      - main
jobs:
  gpt_translate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository with two latest commits
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: get changed files name
        id: changed_files
        run: |
          echo "files=$(git diff --name-only HEAD^ HEAD | grep '^EN/.*\.md$' | while read file; do [ -f "$file" ] && echo "$file"; done | tr '\n' ' ')" >> $GITHUB_OUTPUT

      - name: Run GPT Translate
        uses: 3ru/gpt-translate@master
        with:
          apikey: ${{ secrets.OPENAI_API_KEY }}
          model: "gpt-3.5-turbo-16k"
          #model: "gpt-4"
          inputFiles: ${{ steps.changed_files.outputs.files }}
          outputFiles: "DE/**/*.md IT/**/*.md FR/**/*.md PT/**/*.md AR/**/*.md SP/**/*.md JP/**/*.md CN/**/*.md DT/**/*.md AL/**/*.md"
          languages: "German Italian French Portuguese Arabic Spanish Japanese Chinese Dutch Albanian"
